# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 99a81391b46181f7d613b023505ecc2e5655aed6864ab5ffc76d7c9a495d42445fbb8146f01880e2a5e049539d214f6e59b1847dac589a26c09718f278813266

test:
  secret_key_base: 8365b2cf151dc3b808b45d2ab14a474396cbf168246b1a20f0cbb33f1995c63e822afb5a5a5327c821896ff35980e34b6f291f05e6c57c257fd3f86be23b99fc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
